### ISSUE TITLE
body,there is any way to mouse ios without jailbreak?

### ISSUE THREAD

**Issue by ShiverZm** [mringwal/mouse-support#6]

**Comment by mringwal** [comment]
Nope. You need the entitlements to send touch event to the system, and you cannot get these without jailbreak.

**Comment by ShiverZm** [comment]
i see,some software can use bluetooth to control iphone ,like wormhole https://er.run/ ,and douwan screen https://douwan.video/index_ch.html

**Comment by mringwal** [comment]
iOS 13 supports Bluetooth mouse. if you simulate a mouse on the desktop, you can use it to simulate clicks/swipes/ etc.
I was considering to create something like Wormhole, resp. more a VNC Client where you could move the desktop mouse pointer over to the iPhone to control it, but didn't got far there. AFAIK there's no official way to get iOS screen to desktop without USB cable being plugged in or an app running on the device.

**Comment by ShiverZm** [comment]
you can use bluetooth api to control ios,simulating as a mouse and keyboard.

**Comment by ShiverZm** [comment]
and i see,in mac,it  can control iphone with xcode ,there are some methond that can simulate xcode env to identify this for control phone

**Comment by krishtoautomate** [comment]
@ShiverZm possible to share api info.
@mringwal did you find any related apis?
